### ISSUE TITLE
Vugu fails to run in Firefox

### ISSUE THREAD

**Issue by Chaz6** [vugu/vugu#51]
**Describe the bug**
When trying the example it does not work in Firefox.

**Software Versions**
Vugu version: v0.0.0-20190518235128-5a84f26390d1
Go version: go version go1.11.5 linux/amd64
Browser and version: Firefox 68.0

**To Reproduce**
I followed the instructions on the website to run the example. It is copy and pasted exactly.

**Expected behavior**
The example should run when opened in Firefox.

**Additional Notes**
The output from the javascript console is `The resource from “http://127.0.0.1:8844/wasm_exec.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).`

**Comment by bradleypeabody** [comment]
Thanks.  I pushed a fix for this.  Please try again with the latest version (remove the line with vugu in it from your go.mod and run it again)

**Comment by Chaz6** [comment]
Thank you!

I removed vugu from go.mod, and tried again, but it is still failing as before. This is the console output:-

```
$ go run devserver.go
go: finding github.com/vugu/vugu/simplehttp latest
go: finding github.com/vugu/vugu latest
go: downloading github.com/vugu/vugu v0.0.0-20190719055003-a013ad2a9274
2019/07/19 12:43:22 Starting HTTP Server at "127.0.0.1:8844"
2019/07/19 12:43:47 http: multiple response.WriteHeader calls
```

From Firefox:-
```
The resource from “http://127.0.0.1:8844/wasm_exec.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
The resource from “http://127.0.0.1:8844/wasm_exec.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
Loading failed for the <script> with source “http://127.0.0.1:8844/wasm_exec.js”.
ReferenceError: Go is not defined
```

**Comment by bradleypeabody** [comment]
Hm, I'm thinking something else might be wrong here. Is that URL erroring?  Can you paste `http://127.0.0.1:8844/wasm_exec.js` into your browser and see if you are getting an error message instead of a JS file, and if so what's the error?

**Comment by Chaz6** [comment]
Firefox:-

```
Request URL: http://127.0.0.1:8844/wasm_exec.js
Request method: GET
Remote address: 127.0.0.1:8844
Status code: 500
Version: HTTP/1.1
```

Server:-
```
$ go run devserver.go
2019/07/19 16:46:48 Starting HTTP Server at "127.0.0.1:8844"
2019/07/19 16:47:43 http: multiple response.WriteHeader calls
```

I also tried this:-
```
$ curl 127.0.0.1:8844/wasm_exec.js
failed to read wasm_exec.js from local Go environment
```

**Comment by bradleypeabody** [comment]
`failed to read wasm_exec.js from local Go environment` <- This is definitely an issue.  It's returning an error instead of the JS file.

One thing to fix is - and I'm not sure how it is running at all like this, but it requires Go 1.12 or higher (above it says `go version go1.11.5 linux/amd64`).  Please **upgrade to the latest Go version** and try again.  **if problems** persist, run **`go env GOROOT`** and let me know what that outputs.  Then look under that path and **see if there is a non-empty file at `misc/wasm/wasm_exec.js`**.

**Comment by bradleypeabody** [comment]
I'm assuming this has since been resolved, closing.
